FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY . /usr/share/nginx/html

# Simple runtime config injection support (optional)
# You can provide /docker-entrypoint.d script in compose to write window.ENV

EXPOSE 80


