# Railway deployment configuration
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fincloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    environment:
      AUTH_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/fincloud_db
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  finance-service:
    build: ./finance-service
    environment:
      FINANCE_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/fincloud_db
      AUTH_SERVICE_URL: http://auth-service:8000
    depends_on:
      - postgres
      - auth-service
    ports:
      - "8001:8001"

  report-service:
    build: ./report-service
    environment:
      REPORT_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/fincloud_db
      AUTH_SERVICE_URL: http://auth-service:8000
    depends_on:
      - postgres
      - auth-service
    ports:
      - "8002:8002"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - finance-service
      - report-service

volumes:
  postgres_data:

