apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fincloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: fincloud-auth:local
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_DATABASE_URL
              value: postgresql://postgres:postgres@postgres.fincloud.svc.cluster.local:5432/auth_db
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fincloud
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP

