apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  namespace: fincloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance
          image: fincloud-finance:local
          imagePullPolicy: IfNotPresent
          env:
            - name: FINANCE_DATABASE_URL
              value: postgresql://postgres:postgres@postgres.fincloud.svc.cluster.local:5432/finance_db
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: fincloud
spec:
  selector:
    app: finance-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP

