name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r auth-service/requirements.txt
        pip install -r finance-service/requirements.txt
        pip install -r report-service/requirements.txt
    
    - name: Run tests
      run: |
        echo "Running basic syntax checks..."
        python -m py_compile auth-service/app/main.py
        python -m py_compile finance-service/app/main.py
        python -m py_compile report-service/app/main.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      uses: railway-app/railway-deploy@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: fincloud-system

